In [1]:
import numpy as np 

In [2]:
rank = input("請輸入Rank：")

請輸入Rank：3


In [174]:
rank = int(rank)

In [193]:
row = np.random.randint(rank,8)
col = np.random.randint(rank,8)

In [194]:
row

5

In [195]:
col

7

In [212]:
arr = np.eye(row,col)

In [213]:
arr

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.]])

In [214]:
arr[rank,]

array([0., 0., 0., 1., 0., 0., 0.])

In [215]:
for i in range(rank-1,col):
    for j in range(0,row):
        arr[j,i] = 1

In [216]:
arr

array([[1., 0., 1., 1., 1., 1., 1.],
       [0., 1., 1., 1., 1., 1., 1.],
       [0., 0., 1., 1., 1., 1., 1.],
       [0., 0., 1., 1., 1., 1., 1.],
       [0., 0., 1., 1., 1., 1., 1.]])

In [218]:
for i in range(0,row):
    for j in range(0,row):
        if(i!=j):
            arr[i] = arr[i] + np.random.randint(-2,2)*arr[j]

In [219]:
arr

array([[ 1.,  1.,  3.,  3.,  3.,  3.,  3.],
       [-1.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  2.,  2.,  2.,  2.,  2.],
       [-1., -2., -3., -3., -3., -3., -3.],
       [ 4.,  5.,  9.,  9.,  9.,  9.,  9.]])

In [220]:
arr = arr%7

In [221]:
arr

array([[1., 1., 3., 3., 3., 3., 3.],
       [6., 0., 0., 0., 0., 0., 0.],
       [0., 1., 2., 2., 2., 2., 2.],
       [6., 5., 4., 4., 4., 4., 4.],
       [4., 5., 2., 2., 2., 2., 2.]])

In [222]:
import sympy as sp

In [223]:
M = sp.Matrix([[1., 1., 3., 3., 3., 3., 3.],
       [6., 0., 0., 0., 0., 0., 0.],
       [0., 1., 2., 2., 2., 2., 2.],
       [6., 5., 4., 4., 4., 4., 4.],
       [4., 5., 2., 2., 2., 2., 2.]])

In [224]:
M.rref()

(Matrix([
 [1, 0, 0,   0,   0,   0,   0],
 [0, 1, 0,   0,   0,   0,   0],
 [0, 0, 1, 1.0, 1.0, 1.0, 1.0],
 [0, 0, 0,   0,   0,   0,   0],
 [0, 0, 0,   0,   0,   0,   0]]), (0, 1, 2))

資料：https://codertw.com/%E7%A8%8B%E5%BC%8F%E8%AA%9E%E8%A8%80/362514/