In [2]:
import time
import numpy as np
import matplotlib.pylab as plt
%matplotlib inline

In [7]:
L = []
for t in range(100, 1001, 100):
    Time_start = time.time()
    x = np.arange(1, t+1).reshape(t, 1)
    y = np.arange(1, t+1)
    print(np.c_[np.repeat(x, t),np.tile(y, (1,t)).reshape(t*t,1 )])
    Time_end = time.time()
    L.append(Time_end - Time_start)

[[  1   1]
 [  1   2]
 [  1   3]
 ...
 [100  98]
 [100  99]
 [100 100]]
[[  1   1]
 [  1   2]
 [  1   3]
 ...
 [200 198]
 [200 199]
 [200 200]]
[[  1   1]
 [  1   2]
 [  1   3]
 ...
 [300 298]
 [300 299]
 [300 300]]
[[  1   1]
 [  1   2]
 [  1   3]
 ...
 [400 398]
 [400 399]
 [400 400]]
[[  1   1]
 [  1   2]
 [  1   3]
 ...
 [500 498]
 [500 499]
 [500 500]]
[[  1   1]
 [  1   2]
 [  1   3]
 ...
 [600 598]
 [600 599]
 [600 600]]
[[  1   1]
 [  1   2]
 [  1   3]
 ...
 [700 698]
 [700 699]
 [700 700]]
[[  1   1]
 [  1   2]
 [  1   3]
 ...
 [800 798]
 [800 799]
 [800 800]]
[[  1   1]
 [  1   2]
 [  1   3]
 ...
 [900 898]
 [900 899]
 [900 900]]
[[   1    1]
 [   1    2]
 [   1    3]
 ...
 [1000  998]
 [1000  999]
 [1000 1000]]
