In [1]:
import time
import numpy as np
import matplotlib.pylab as plt
%matplotlib inline

In [14]:
n = 10
L = np.array([])
N = list()
for k in range (1,n+1): 
    starttime = time.clock()
    for i in range (1,100*k+1):
        for j in range (1,100*k+1):
            L = np.append(L,i)
            L = np.append(L,j)
    L = L.reshape(2,-1)
    endtime = time.clock()
    N.append(endtime - starttime)
print(N)
plt.plot(range(1,n+1),L)
plt.xlabel("次數")
plt.ylabel("時間")

In [2]:
L = np.append(L,2)

NameError: name 'L' is not defined

In [22]:
L = np.append(L,5)

In [23]:
L

array([2., 3., 5.])

In [3]:
for i in range(1,n+1):
    starttime = time.clock()
    for i in range (1,100*k+1):
        for j in range (1,100*k+1):
            L.append([i])
    print(end="\n")
    endtime = time.clock()
    L.append(endtime - starttime)

NameError: name 'n' is not defined

In [8]:
L.append(1)

AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [ ]:
n = 1
L = list()
for k in range (1,n+1): 
    starttime = time.clock()
    for i in range (1,100*k+1):
        for j in range (1,100*k+1):
            print(f"({i},{j}) ", end=' ')
    print(end="\n")
    endtime = time.clock()
    L.append(endtime - starttime)
print(L)
plt.plot(range(1,n+1),L)
plt.xlabel("次數")
plt.ylabel("時間")

In [12]:
n = 3
L = np.array([])
N = list()
for k in range (1,n+1): 
    starttime = time.clock()
    for i in range (1,100*k+1):
        for j in range (1,100*k+1):
            L = np.append(L,i)
            L = np.append(L,j)
    L = L.reshape(-1,2)
    print(L)
    endtime = time.clock()
    N.append(endtime - starttime)
print(N)

C:\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: DeprecationWarning: time.clock has been deprecated in Python 3.3 and will be removed from Python 3.8: use time.perf_counter or time.process_time instead
  """


[[  1.   1.]
 [  1.   2.]
 [  1.   3.]
 ...
 [100.  98.]
 [100.  99.]
 [100. 100.]]


C:\Anaconda3\lib\site-packages\ipykernel_launcher.py:12: DeprecationWarning: time.clock has been deprecated in Python 3.3 and will be removed from Python 3.8: use time.perf_counter or time.process_time instead
  if sys.path[0] == '':


[[  1.   1.]
 [  1.   2.]
 [  1.   3.]
 ...
 [200. 198.]
 [200. 199.]
 [200. 200.]]
[[  1.   1.]
 [  1.   2.]
 [  1.   3.]
 ...
 [300. 298.]
 [300. 299.]
 [300. 300.]]
[0.5299357999999756, 5.497058600000003, 288.88126750000004]


In [9]:
print(L)

[[  1.   1.]
 [  1.   2.]
 [  1.   3.]
 ...
 [100.  98.]
 [100.  99.]
 [100. 100.]]


In [7]:
L = []
for t in range(100, 1001, 100):
    Time_start = time.time()
    x = np.arange(1, t+1).reshape(t, 1)
    y = np.arange(1, t+1)
    print(np.c_[np.repeat(x, t),np.tile(y, (1,t)).reshape(t*t,1 )])
    Time_end = time.time()
    L.append(Time_end - Time_start)

[[  1   1]
 [  1   2]
 [  1   3]
 ...
 [100  98]
 [100  99]
 [100 100]]
[[  1   1]
 [  1   2]
 [  1   3]
 ...
 [200 198]
 [200 199]
 [200 200]]
[[  1   1]
 [  1   2]
 [  1   3]
 ...
 [300 298]
 [300 299]
 [300 300]]
[[  1   1]
 [  1   2]
 [  1   3]
 ...
 [400 398]
 [400 399]
 [400 400]]
[[  1   1]
 [  1   2]
 [  1   3]
 ...
 [500 498]
 [500 499]
 [500 500]]
[[  1   1]
 [  1   2]
 [  1   3]
 ...
 [600 598]
 [600 599]
 [600 600]]
[[  1   1]
 [  1   2]
 [  1   3]
 ...
 [700 698]
 [700 699]
 [700 700]]
[[  1   1]
 [  1   2]
 [  1   3]
 ...
 [800 798]
 [800 799]
 [800 800]]
[[  1   1]
 [  1   2]
 [  1   3]
 ...
 [900 898]
 [900 899]
 [900 900]]
[[   1    1]
 [   1    2]
 [   1    3]
 ...
 [1000  998]
 [1000  999]
 [1000 1000]]
